feature: add NatsEventAuditLogMessage
kumparan/ferstream pull request #13
Opened 2022-09-23 08:23 UTC by bimaahida

2022-09-23 08:32 UTC, atjhoendz approved these changes
lgtm

2022-09-23 09:28 UTC, zipzap11 requested changes

2022-09-23 09:28 UTC, zipzap11 commented on event_message.go
> +	message, err := tapao.Marshal(n)
ga fallback json juga ? pas ParseFromBytes fallback json

2022-09-23 09:50 UTC, bimaahida commented on event_message.go
> +	message, err := tapao.Marshal(n)
aku tambahin  `message, err := tapao.Marshal(n, tapao.With(tapao.JSON))`

2022-09-27 03:37 UTC, zipzap11 approved these changes

2022-09-28 02:53 UTC, merged